ModOrganizer2/modorganizer-uibase

src/iplugindiagnose.h
Parts of this header rely on QObject having been imported, but until now it's relied on other files including it.
(e.g. when this is included in `plugincontainer.h`, that file first includes `previewgenerator.h`, which in turn includes `QWidget`, which includes some things which eventually include Qt's internal QObject header. Therefore if `previewgenerator.h` got moved later in the list of includes, suddenly Mod Organizer wouldn't compile.)
=> Include QObject in IPluginDiagnose

src/idownloadmanager.h, src/imodrepositorybridge.h, src/iplugintool.h
These changes are needed because of conflicting keyword naming between Qt and Python 3.
=> Migrate to python 3

src/utility.cpp, src/utility.h
I renamed to original to `formatSystemMessageQ()` and added a new `formatSystemMessage()` that returns a `std::wstring.` I also fixed `LogShellFailure()` not logging stuff correctly because it was using variadic arguments.
This is dependent on PR https://github.com/ModOrganizer2/modorganizer/pull/781.
=> Moved formatSystemMessage() from main repo

src/utility.cpp, src/utility.h
Added a `getKnownFolder()`, now also logs the error message on failure
=> Refactored getDesktopDirectory() and getStartMenuDirectory()

src/log.cpp
Don't add empty sinks, happens when switching instances when the file sink is reset
=> Crash when switching instances

src/utility.cpp, src/utility.h
- Renamed shell functions to remove redundant 'File' and 'Link'
- Added `Delete()` and `Rename()`
- Made them all return a `Result` instead of a `bool`
=> Shell functions

src/registry.cpp, src/textviewer.cpp
Some users value the ability to keep INI files as read-only and do not
want to be constantly nagged to clear the read-only status.  This allows
them to silence the nags.
Also, new fancy dialog box.
=> Update WriteRegistryValue to use TaskDialog window and remember choices

src/log.cpp, src/pch.h, src/taskprogressmanager.cpp, src/utility.cpp, src/utility.h
The `Result` class returned by shell operations now has the process handle so MO can wait on these handles. Goes with https://github.com/ModOrganizer2/modorganizer/pull/887.
=> Process handles for shell operations

src/safewritefile.cpp
In case of an error while opening a temporary file the specific error
message instead of a generic one will be used.
=> Provide details of error source

src/CMakeLists.txt, src/filterwidget.cpp, src/filterwidget.h, src/utility.cpp, src/utility.h, src/version.rc, src/widgetutility.cpp, src/widgetutility.h
- Filtered lists now set the `filtered` property instead of hardcoding red borders
- Moved flags back into `FilterWidget` instead of the model so they can be set before the list
- Regex for filters
- `TimeThis` from modorganizer
- `forEachLineInFile()` from game_gamebryo
- `setCustomizableColumns()`
=> Filter widget and more

src/filterwidget.cpp, src/filterwidget.h
- Added option to keep selection in view while filtering
- Added optional delay before filtering after text changed to stack multiple changes into a single filter pass.
- Avoid crash when nullptr is passed to setList()
Requires merging matching PR in modorganizer
=> Filterwidget updates

src/ifiletree.cpp, src/ifiletree.h
Small modifications to `IFileTree` to have thread-safe read operations:
- Within read operations, the only thing that can be modified is the `m_Entries` vector when being populated, so it's the only section of the code that need lock-mechanisms.
- I did not notice even the smallest impact on performance, I think that `std::call_once` is pretty well implemented.
=> Make IFileTree read-only operations thread-safe

src/ifiletree.cpp, src/ifiletree.h
- Minor fix to `FileNameComparator` (use the static `CaseSensitivity` instead of `Qt::CaseInsensitive`).
- Add `hasSuffix` methods which can be useful (perform case-insensitive comparison for us). Recompute the suffix each time though.
=> Minor stuffs

src/utility.h, src/widgetutility.cpp, src/widgetutility.h
- Make it possible to dynamically hide column checkbox in `setCustomizableColumns` using a user-defined Qt role.
- Removed old `MakeVector`.
=> Minor changes and cleaning for ModDataContent

src/ifiletree.cpp, src/ifiletree.h, src/iinstallationmanager.h, tests/test_ifiletree.cpp
**Major:**
- Add a `createFile()` method in `IInstallationManager` that can be used to create files during installation that will then be moved to the mod folder.
As you probably know, this is an issue I had with the C# FOMOD installer. Using the simple installer interface is enough, but files need to be created.
The interface is simple and does not impact existing installers. The files are created in the temporary directory and automatically removed at the end of the installation process.
**Minor:**
- Fix a bug in `addFile` when creating files in subtrees.
- Add `replaceIfExists` in `addFile` that allow replacing existing files.
- A bit more tests for `IFileTree`.
=> Installation manager improvements

src/imoinfo.h
Add an overload for `findFiles` that uses a list of glob patterns instead of a function. This will mostly be useful for python plugins since using a python function as a filter is costly (see the current "issue" with the form43 checker).
=> Add findFiles overload with glob patterns.

src/iinstallationmanager.h
Add a parameter `silent` to the two extraction methods of `IInstallationManager`. This is mostly useful for the C# installer or other installers that might need to extract single file from time-to-time.
It has 0 impacts on existing installers since the default value is `false`. For the C# installer, I think it improve the user experience since it avoids having the progress dialog show-up 10 times in a row for a fraction of a second.
=> Add silent parameter to extraction methods of IInstallationManager.

src/utility.cpp, src/utility.h
Move these two functions from `game_gamebryo` since 1) they could be used elsewhere, and 2) I think it's a good idea to have python bindings for them (see the python PR).
=> Add getFileVersion and getProductVersion from game_gamebryo.

src/ifiletree.cpp, src/ifiletree.h
When I first added `copy()`, I make it returned a `bool` similar to `move()`. This is very inconvenient because you do not have access to the copy after the call.
This change it so that the cloned entry is returned. This should have 0 impact on other projects since the `shared_ptr` is implicitly convertible to `bool` anyway.
=> Make IFileTree::copy() return the new entry instead of bool.

src/imoinfo.h
Adds 2 new callbacks for plugins to use to `IOrganizer`:
- `userInterfaceInitialized`, called when the `MainWindow` has been created. Plugins can manipulate the interface at this point if they want.
- `profileChnaged`, called when the profile has been changed (also called on startup with `oldProfile` empty, see comment).
I wanted to make those Qt signals, but I hit a hard wall with the python interface... I can use Qt signals in the Python interface, but I cannot use a signal with a user-defined type. Furthermore, I have no idea how PyQt signals and slots are connected, so I'd probably have to use some kind of shared pointer for the old profile, and it gets worse since you have a signal with a shared pointer. 
In the end, I did not manage to do it so I used the old `onXXX` version. For …
=> Add callbacks userInterfaceInitialized and profileChanged

src/report.cpp
There *might* be some places where this causes the error to be logged twice, but definitely eliminates some where it was never logged.
Most recent discussion is here: https://discordapp.com/channels/265929299490635777/412414009694748693/728288794729775134
=> Log errors

src/utility.h
`forEachLineInFile()` doesn't convert to lowercase any more, it was confusing for the callers, which have been fixed for the new behaviour.
=> forEachLineInFile() lowercase

src/utility.h
it was confusing for the callers, which have been fixed for the new behaviour
=> Cherry picked: forEachLineInFile() lowercase 

src/imodlist.h
- Adds a new `setActive` overload to enable / disable mods in bulk.
- Change `onModStateChanged` callback to take a list of mods:
- PR for `diagnose_basic`: https://github.com/ModOrganizer2/modorganizer-diagnose_basic/pull/10
- For Python plugin, the two versions will be kept but a depreciation warning will be shown.
=> Add a bulk-version of IModList::setActive.

src/iplugin.h, src/iplugintool.h
Add `localizedName()` and `master()`:
- `localizedName()` should be used in the UI when possible. This default to `displayName()` only for `IPluginTool`.
- I plan on using `master()` for display purpose to avoid having very long list of plugins, but also for future usage (e.g. automatic update of plugins). This is especially useful since some DLLs / python modules can expose multiple plugins.
=> Add localizedName() and master() for IPlugin.

src/imodinterface.h
I forgot this in the previous PR, and I think it's mandatory for some stuffs (e.g. you probably want to clear settings before writing new ones for installers).
=> Add IModInterface::clearPluginSettings().

src/imodinterface.h
Fixes point 1 of https://github.com/ModOrganizer2/modorganizer/issues/1139
- The nexus-related stuff are currently commented because I'm not sure I want to expose them here.
- I am not sure what `converted()` and `validated()` mean here (I fetched those from meta files), so I did not expose them.
- `primaryCategory` returns the category ID, but I'm not sure there is a way to get the list of all categories from a plugin, so this might need change.
=> Add getters for most meta-information in mod.

src/iplugininstaller.h
I added these callbacks to be able to get information from a previously installed mod (in case of re-installation) and to be able to modify settings of the mod afterwards (following https://github.com/ModOrganizer2/modorganizer-uibase/pull/84). This allows for the following (very useful !) features:
- The bundle installer will be able to easily set the true installation file at the end of the installation. Currently the installation file stored in the `meta.ini` is the extracted archive.
- This will allow some installers to remember settings from previous installation. For BAIN and Bundle (in case of multiple archives), this is pretty easy to implement. For FOMOD, this would require a bit more work and probably some refactoring.
Why two new callbacks instead of modifying the existing …
=> Add IPluginInstaller onInstallationStart and onInstallationEnd callbacks.

src/iprofile.h
After allowing absolute file path in `IPluginGame::iniFiles()`, it becomes annoying to get the path to a INI file depending on the local INI setting, so I'm adding this.
=> Add IProfile::iniFilePath().

src/idownloadmanager.h
WIP: This only handles `IDownloadManager` but should also be done for `IModRepositoryBridge`.
- `modorganizer` PR: https://github.com/ModOrganizer2/modorganizer/pull/1260
- `plugin_python` PR: https://github.com/ModOrganizer2/modorganizer-plugin_python/pull/68
=> Switch from Qt signals to boost::signals

src/filterwidget.cpp
No clue on this one. Sorting is sometimes ignored by the underlying proxy model unless the sort order is set. The column needs to be `-1` to avoid double sorts, I think. I don't know. The sort proxy strikes again.
=> Filter widget sometimes ignores source sorting

.gitignore, src/filterwidget.cpp, src/filterwidget.h, src/imoinfo.cpp, src/imoinfo.h, src/iplugin.h, src/iplugingame.h, src/report.cpp, src/report.h, src/utility.cpp, src/utility.h
- Added `CreateDirectories()`, `DeleteDirectoryRecursive()`
- Added `Rename()` with a `copyAllowed` flag.
- Added an option to disable the red border
- Added a few functions for mapping and a simpler `matches()` that just takes a string.
- Don't hook the escape key to reset filters when in a dialog, it prevents from closing it.
- Added `addContent()` to add custom content at the bottom of the dialog
- Added `setWidth()` to override the default width
- Moved `naturalCompare()` from MO
=> Command line and instance dialogs

src/report.cpp
Happens when dialogs are shown without a main window, they would sometimes be shown in the back of the z order.
=> Raise the `TaskDialog` on top if there's no parent

src/ifiletree.cpp, src/iplugin.h, src/iplugingame.h, src/isavegame.h, src/isavegameinfowidget.h, src/memoizedlock.h, src/pluginrequirements.cpp, src/pluginrequirements.h
This is a proposition to improve the way save games are exposed to MO2. I will group here the information about the other repositories.
**Before this PR:**
- Game plugins expose a directory and a save file extension that MO2 then use to find all the saves (recursively for some time).
- It then use the `GameSaveInfo` feature to obtain a `ISaveGame` or a `ISaveGameWidget` to display, etc.
**After this PR:**
- Game plugins still expose the standard directory where saves are located.
- Game plugins are the one responsible for listing the saves, they can do whatever they want. They also return `ISaveGame` objects and not filenames.
There are two advantages for this:
- Game can list saves the way they want, so no more issues if saves are stored as folder, or in sub-folders, etc.
- Since the …
=> IPluginGame::listSaves

src/ipluginproxy.h
This has currently no use but since it can be done apart from the other changes to allow (re)loading plugins without restarting MO2, I prefer to make separate PRs that can be merged.
=> Add IPluginProxy::unload() and rename instantiate() to load().

src/exceptions.h, src/ifiletree.h, src/imoinfo.h, src/nxmurl.cpp, src/safewritefile.cpp, src/textviewer.cpp, src/tutorialmanager.cpp, src/utility.cpp, src/utility.h
Rename `MyException` to `MOException`, keep an alias to avoid having to change all the projects right now. 
A few projects need updating because they inherit `MyException`, PR are coming (3 projects).
=> Rename MyException to MOException

src/filterwidget.cpp, src/filterwidget.h, src/utility.cpp, src/utility.h
- Added `FilterWidget::setSortPredicate()` as an easy way to get custom sorting without having to implement `sort()` on the source model.
- Added `SetUrlHandler()` for a custom URL handler and implemented that in `shell::Open()` for `QUrl`s.
=> More stuff

src/imodinterface.h
Add a few methods to `IModInterface` to get the type of "mods".
This has been sitting locally for a while. It's not used right now but will probably be useful once context menus are available for plugins/extensions.
=> Add method to get the type of IModInterface.

src/imodinterface.h, src/imodlist.h
These methods should not be in the mod interface because they can actually affect the mod list. Currently these do not trigger refresh or anything so if plugins use them it's kind of weird.
The other `setXXX` methods do not affect the order or items in the mod list in the same way so those are fines.
=> Remove setName and remove from mod interface.

src/report.cpp, src/report.h
`reportError()` now tries to find the main window as its parent. If it's not found, it calls `criticalOnTop()` instead (moved from MO), which shows a message box on top of the z-order (but not top-most).
See https://github.com/ModOrganizer2/modorganizer/pull/1354.
=> Find parent for reportError()

src/utility.cpp, src/utility.h
- Added `formatNtMessage()` to get error messages for `NTSTATUS` errors, used in MO by `envfs` for the downloads and file register
- Refactored `formatSystemMessage()` into `getMessage()` and `formatMessage()` so they can be used for both system and NT errors
=> formatNtMessage()

src/tutorialcontrol.cpp, src/tutorialcontrol.h
This is required as some actions are mutually exclusive yet
either action can advance the tutorial.
=> Tutorial: Save all connections and break all connections

src/iplugindiagnose.h, src/iplugingame.h, src/pch.h
Remove `boost` dependency. This should make it easier to write C++ plugin without having to build the whole MO2 before... I'll probably try to set-up a CMake template project that does not require `mob` if people want to build C++ project.
I removed the signal in `IPluginDiagnose` because it was not really used... There was always a single callback, so I just store the `std::function<>()`.
Close https://github.com/ModOrganizer2/modorganizer/issues/862
=> Remove boost dependency.

src/textviewer.cpp
This is a minor change primarily to try to help identify when special characters end up in the INI during a copy/paste and the like.
=> Make whitespace visible in the editor

src/iplugingame.h
- Add enabledPlugins for core plugins which are enabled but NOT auto-loaded (may need to be written to plugins.txt or have an ambiguous load order position)
- General Starfield updates
- Add enabledPlugins for "BlueprintShips-Starfield.esm"
- Disable plugin management if sTestFile is in use (also applies to FO4)
- Write the enabledPlugins to plugins.txt to enforce base game load order
- Allow for LOOT sorting (dynamic based on settings)
- Incorporate enabledPlugins into force enabled plugins in plugin list
- Update various interface layers
TODO: Fix sort button to dynamically update if status changes
TODO: Auto refresh lists if the INI Editor is closed
=> WIP: Plugin sorting updates

src/ipluginlist.h
https://github.com/ModOrganizer2/modorganizer-game_starfield/pull/15
https://github.com/ModOrganizer2/modorganizer/pull/1907
https://github.com/ModOrganizer2/modorganizer-plugin_python/pull/117
=> Add isDummy to IPluginList

src/iplugingame.h
- Add `lootGameName()` which will give the plugin a tad bit more control over LOOT cli args
- Add `displayGameName()` which will be used to separate display-specific calls & more integral calls to `gameName()`, will also pave way for deeper plugin localization
Changes are planned to other pieces of MO in different repositories that will use these additions
=> Add `displayGameName()` and `lootGameName()` to plugin-base

.github/workflows/build.yml, src/CMakeLists.txt, src/formatters.h, src/log.cpp, src/log.h, src/report.cpp, src/utility.cpp
Switch from `fmtlib` to `std::format`.
I already updated the modorganizer project to follow these changes, PR to come, but other repositories probably needs to be updated as well.
Some details:
- I removed the custom converters in favor of specialization of `std::formatter` - There is a specialization to allow using `std::basic_string` of any char-type with any format string (e.g., `std::format("{}", L"Hello World!"`). This was done to follow the previous converter behavior, not sure if we want to keep it.
- I added overloads for all logs function that takes `std::format_string` - This allows for compile-time checking of the format string. In an ideal world, that would be the sole overload, but we have many places with translated format string. I kept the templated `F` version, but this …
=> Switch from fmtlib to std::format.

src/ipluginlist.h
This PR adds `author` and `description` methods to `IPluginList` for use in Python plugins. I will also open PRs on the main- and Python plugin repositories to add the implementations.
For my [LOOT Warning Checker plugin](https://github.com/JonathanFeenstra/modorganizer-loot-warning-checker), the `description` method would be especially useful, since it allows me to find the version of a plugin without having to parse the SNAM-subrecord again.
=> Add author and description methods to `IPluginList`

src/game_features/gameplugins.h, src/ipluginlist.h
Add new function to parse the blueprint flag
=> Blueprint support

src/idownloadmanager.h
Requested by @FlayaN on Discord
=> Add startDownloadNexusFileForGame

src/formatters/random_access_containers.h, src/iplugingame.h, src/version.rc
Adding interfaces for VFS mod mapping updates (used to get Oblivion Remastered to map to multiple locations).
* modDataDirectory defines mod directory that maps to 'Data'
- This is used to tell the main interface where to look for 'Data' files and defaults to the root directory
* getModMappings allows mapping directories to multiple locations
- This contains mod subdirectory -> VFS directory mappings (where the VFS mappings can be a list of locations)
- By default, will map the root mod directory to the game 'data' directory (and any secondary data directories if defined)
- Oblivion Releloaded maps 'Data' to the game `Data`, 'Paks' to the game `Paks\~mods`, 'OBSE' to the root `OBSE` directory and so on.
=> Oblivion Remastered Support

src/safewritefile.cpp, src/safewritefile.h
This changes SafeWriteFile to use QSaveFile which should prevent the rare issue of data being lost during a crash or power failure. 
A downside is that a file can be left in the active profile directory if a power failure occurs. That file will then be caught by the filter when restoring backups. Currently, I just attach a warning in the description of such files in the backup dialog.
=> Use QSaveFile in SafeWriteFile

src/versioninfo.cpp
Frequent recompilation of this expression accounts for ~30% of time spent in `DownloadManager::refreshList` for a list of about 4200 downloads.
A similarly significant amount of time is spent on synchronization of QSettings in `DownloadManager::DownloadInfo::createFromMeta`. We can disable this synchronization with `QSettings::setAtomicSyncRequired`, but I am unsure if it is safe to do so.
=> Avoid repeated QRegularExpression compilation

include/uibase/ifiletree.h, include/uibase/ifiletree_utils.h, src/CMakeLists.txt, src/ifiletree.cpp, tests/test_ifiletree.cpp
This changes should allow using `IFileTree` in project that do not support CXX23 (in particular the C++/CLI projects).
=> Move glob() and walk() generator versions to standalone functions.
