ModOrganizer2/modorganizer-uibase

- src/imoinfo.h
- src/iplugininstallercustom.h
https://github.com/Modorganizer2/modorganizer/pull/454
> Stage for 2.1.4 release

- src/installationtester.cpp
MWSE 2.1 brings plugins, similar to OBSE/SKSE.
> Add MWSE folder support for installations.

- src/installationtester.cpp
https://github.com/Modorganizer2/modorganizer/pull/495
> Stage for 2.1.5 release

- src/idownloadmanager.h
- src/iinstallationmanager.h
- src/imodrepositorybridge.h
- src/installationtester.cpp
- src/iplugintool.h
- src/iprofile.h
- src/questionboxmemory.cpp
https://github.com/ModOrganizer2/modorganizer/pull/586
> Stage for release 2.1.6

- src/log.cpp
- src/log.h
- Added single file option
- Handles exception when the file sink can't be created
> Logging fixes

- src/CMakeLists.txt
- src/log.cpp
- src/log.h
- src/pch.h
- src/questionboxmemory.cpp
- src/questionboxmemory.h
- src/questionboxmemory.ui
- src/utility.cpp
- src/utility.h
- src/versioninfo.cpp
- src/versioninfo.h
- Added more converters for Qt for logging
- Log when formatting a log entry fails
- `QuestionBoxMemory` used to fiddle with `QSettings` directly; it now defers to `Settings` from MO through callbacks
- Added `localizedByteSize()` and `localizedByteSpeed()`
> Settings interface

- src/versioninfo.cpp
Fixes https://github.com/ModOrganizer2/modorganizer/issues/776.
> Date version scheme now uses system locale

- src/textviewer.cpp
Fixes ModOrganizer2/modorganizer#890
> Make highlighted text visible if editor unfocused

- src/filterwidget.cpp
- src/filterwidget.h
- src/utility.cpp
- src/version.rc
- Changed the localized size strings to always round down so 1.9KB doesn't get shown as 2KB.
- `FilterWidget`: use source sort if available, allow for choosing filtered column, fixed double filtering when text changed.
> Generic file list

- src/filterwidget.cpp
- src/filterwidget.h
- src/utility.cpp
- src/utility.h
- src/version.rc
- Added Ctrl+F to `FilterWidget`
- Added `getOptionalKnownFolder()`
- Removed leading whitespace in `LogShellFailure()`
- Bumped to alpha 7
> Bunch of fixes

- src/utility.cpp
- src/utility.h
a bunch of projects don't have c++17
> Removed <optional>

- src/imoinfo.h
See https://github.com/ModOrganizer2/modorganizer/pull/1109
> Add IOrganizer signal when a plugin setting is changed.

- src/filterwidget.cpp
- src/filterwidget.h
Add an option to disable filtering temporarily when changing the underlying model, used the file tree in MO
> FilterWidget disable filtering

- src/imoinfo.h
I got a deadlock calling it from a worker thread.
> Update createMod documentation to reflect reality.

- src/utility.h
- src/version.rc
Fixed piss-poor implementation of `forEachLineInFile()`
> 2.3.1 fixes

- src/textviewer.cpp
Address ModOrganizer2/modorganizer#1209
> Make INI Editor Ctrl+F search wrap around the text.

- src/imoinfo.h
- `modorganizer` PR: https://github.com/ModOrganizer2/modorganizer/pull/1267
- `plugin_python` PR: https://github.com/ModOrganizer2/modorganizer-plugin_python/pull/70
> Add IOrganizer::onProfileXXX callbacks.

- src/imodlist.h
- src/imoinfo.h
Related PRs:
- `modorganizer`: https://github.com/ModOrganizer2/modorganizer/pull/1269
- `plugin_python`: https://github.com/ModOrganizer2/modorganizer-plugin_python/pull/72
Minor PRs:
- `bsa_extractor`: https://github.com/ModOrganizer2/modorganizer-bsa_extractor/pull/11
- `bsapacker`: https://github.com/ModOrganizer2/modorganizer-bsapacker/pull/22
- `diagnose_basic`: https://github.com/ModOrganizer2/modorganizer-diagnose_basic/pull/12
- `game_gamebryo`: https://github.com/ModOrganizer2/modorganizer-game_gamebryo/pull/27
- `game_morrowind`: https://github.com/ModOrganizer2/modorganizer-game_morrowind/pull/23
- `installer_ncc`: https://github.com/ModOrganizer2/modorganizer-installer_ncc/pull/19
- `installer_fomod`: https://github.com/ModOrganizer2/modorganizer-installer_fomod/pull/24
> IModList updates

- src/utility.cpp
- src/utility.h
Allows for logging the current timer and restarting it with a new string.
> Added TimeThis::start()

- src/tutorialcontrol.cpp
Reverts ModOrganizer2/modorganizer-uibase#94
> Revert "Moving things around"

- src/imoinfo.h
requires: https://github.com/ModOrganizer2/modorganizer/pull/1304
> Allow refresh for waitForApplication()

- src/pch.h
- src/tutorialcontrol.cpp
- src/utility.cpp
- src/versioninfo.cpp
- tests/pch.h
Using std equivalents where necessary.
> Remove remaining boost headers

- src/ipluginlist.h
Also deprecate isMaster, though I'm unsure if it's necessary to keep it here
> Add hasMasterExtension, hasLightExtension, isMasterFlagged, and isLightFlagged

- src/imoinfo.h
https://github.com/ModOrganizer2/modorganizer/pull/1884
> Refresh Callback (+ Extra for AboutToRun)

- src/ipluginpreview.h
- src/utility.cpp
- src/utility.h
Add archive/data preview interfaces
> WIP: Archive preview support

- src/utility.cpp
- src/utility.h
For https://github.com/ModOrganizer2/modorganizer/issues/2209
> Utf 16 fixes
